"""add full models

Revision ID: 4c607e6b5214
Revises: 41455a49f26a
Create Date: 2025-05-06 13:11:01.262309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c607e6b5214'
down_revision: Union[str, None] = '41455a49f26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habilidad_id'), 'habilidad', ['id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('fecha_revocado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensaje_id'), 'mensaje', ['id'], unique=False)
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacion_id'), 'notificacion', ['id'], unique=False)
    op.create_table('registro_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_actividad_id'), 'registro_actividad', ['id'], unique=False)
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulante_id', sa.Integer(), nullable=True),
    sa.Column('ruta_archivo', sa.String(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['postulante_id'], ['postulante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_id'), 'curriculum', ['id'], unique=False)
    op.create_table('oferta_laboral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oferta_laboral_id'), 'oferta_laboral', ['id'], unique=False)
    op.create_table('educacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=True),
    sa.Column('institucion', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educacion_id'), 'educacion', ['id'], unique=False)
    op.create_table('experiencia_laboral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=True),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiencia_laboral_id'), 'experiencia_laboral', ['id'], unique=False)
    op.create_table('postulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulante_id', sa.Integer(), nullable=True),
    sa.Column('oferta_id', sa.Integer(), nullable=True),
    sa.Column('fecha_postulacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['oferta_laboral.id'], ),
    sa.ForeignKeyConstraint(['postulante_id'], ['postulante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postulacion_id'), 'postulacion', ['id'], unique=False)
    op.create_table('entrevista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulacion_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('modalidad', sa.String(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrevista_id'), 'entrevista', ['id'], unique=False)
    op.create_table('evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulacion_id', sa.Integer(), nullable=True),
    sa.Column('evaluador_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evaluador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluacion_id'), 'evaluacion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluacion_id'), table_name='evaluacion')
    op.drop_table('evaluacion')
    op.drop_index(op.f('ix_entrevista_id'), table_name='entrevista')
    op.drop_table('entrevista')
    op.drop_index(op.f('ix_postulacion_id'), table_name='postulacion')
    op.drop_table('postulacion')
    op.drop_index(op.f('ix_experiencia_laboral_id'), table_name='experiencia_laboral')
    op.drop_table('experiencia_laboral')
    op.drop_index(op.f('ix_educacion_id'), table_name='educacion')
    op.drop_table('educacion')
    op.drop_index(op.f('ix_oferta_laboral_id'), table_name='oferta_laboral')
    op.drop_table('oferta_laboral')
    op.drop_index(op.f('ix_curriculum_id'), table_name='curriculum')
    op.drop_table('curriculum')
    op.drop_index(op.f('ix_registro_actividad_id'), table_name='registro_actividad')
    op.drop_table('registro_actividad')
    op.drop_index(op.f('ix_notificacion_id'), table_name='notificacion')
    op.drop_table('notificacion')
    op.drop_index(op.f('ix_mensaje_id'), table_name='mensaje')
    op.drop_table('mensaje')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_habilidad_id'), table_name='habilidad')
    op.drop_table('habilidad')
    # ### end Alembic commands ###
